// layout means navigation bar and of all the website 


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// we also write like export default function RootLayout(children)    // niche wle i jgh pr hum typescript mein niche jese likte hein
export default function RootLayout({ 
  children,                              // rootlayout accept  input parameter  as children
}: Readonly<{                           // its typescript in which it defines the data types  like readonly datatype
  children: React.ReactNode;              // children we set datatypes   reactnode type data accept liike example string type
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
      <div className="relative w-full flex items-center justify-center ">
        <Navbar />
      </div>
      {children}
         </body>                 
    </html>
  );
}
  // add